language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
  - oraclejdk9
sudo: false
install: ./mvnw clean
script: ./mvnw install site
notifications:
  email: false
before_install:
  - git submodule update --init --recursive
